var searchData=
[
  ['readbackbuffer_0',['ReadbackBuffer',['../d2/d69/struct_k_o_d_i_1_1_r_e_n_d_e_r_i_n_g_1_1_c_a_p_t_u_r_e_1_1_readback_buffer.html',1,'KODI::RENDERING::CAPTURE']]],
  ['readlineresult_1',['ReadLineResult',['../d1/da4/struct_x_f_i_l_e_1_1_c_file_1_1_read_line_result.html',1,'XFILE::CFile::ReadLineResult'],['../df/dd8/struct_x_f_i_l_e_1_1_i_file_1_1_read_line_result.html',1,'XFILE::IFile::ReadLineResult']]],
  ['reallydumbjob_2',['ReallyDumbJob',['../de/dc1/class_really_dumb_job.html',1,'']]],
  ['recommendedcasingtester_3',['RecommendedCasingTester',['../da/dbd/class_recommended_casing_tester.html',1,'']]],
  ['redundanttag_4',['RedundantTag',['../d4/db4/struct_k_o_d_i_1_1_u_t_i_l_s_1_1_i18_n_1_1_redundant_tag.html',1,'KODI::UTILS::I18N']]],
  ['ref_5',['Ref',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_6',['ref',['../db/dd5/class_x_b_m_c_addon_1_1xbmcgui_1_1ref.html',1,'XBMCAddon::xbmcgui']]],
  ['ref_3c_20p1_20_3e_7',['Ref&lt; P1 &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3acallback_20_3e_8',['Ref&lt; XBMCAddon::Callback &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3acallbackhandler_20_3e_9',['Ref&lt; XBMCAddon::CallbackHandler &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3apython_3a_3apythonlanguagehook_20_3e_10',['Ref&lt; XBMCAddon::Python::PythonLanguageHook &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3aretardedasynccallbackhandler_20_3e_11',['Ref&lt; XBMCAddon::RetardedAsyncCallbackHandler &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3axbmcgui_3a_3acontrol_20_3e_12',['Ref&lt; XBMCAddon::xbmcgui::Control &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3axbmcgui_3a_3acontrolspin_20_3e_13',['Ref&lt; XBMCAddon::xbmcgui::ControlSpin &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_3c_20xbmcaddon_3a_3axbmcgui_3a_3awindow_20_3e_14',['Ref&lt; XBMCAddon::xbmcgui::Window &gt;',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['refreshoverride_15',['RefreshOverride',['../d2/db1/struct_refresh_override.html',1,'']]],
  ['refreshrate_16',['REFRESHRATE',['../d9/d4c/struct_r_e_f_r_e_s_h_r_a_t_e.html',1,'']]],
  ['refreshvideolatency_17',['RefreshVideoLatency',['../d5/d5c/struct_refresh_video_latency.html',1,'']]],
  ['regionsubtag_18',['RegionSubTag',['../db/d32/struct_k_o_d_i_1_1_u_t_i_l_s_1_1_i18_n_1_1_region_sub_tag.html',1,'KODI::UTILS::I18N']]],
  ['registryfilefield_19',['RegistryFileField',['../d8/de2/struct_k_o_d_i_1_1_u_t_i_l_s_1_1_i18_n_1_1_registry_file_field.html',1,'KODI::UTILS::I18N']]],
  ['registryfilerecord_20',['RegistryFileRecord',['../d7/d4c/struct_k_o_d_i_1_1_u_t_i_l_s_1_1_i18_n_1_1_registry_file_record.html',1,'KODI::UTILS::I18N']]],
  ['registryfilerecordlinestester_21',['RegistryFileRecordLinesTester',['../dd/dfd/class_registry_file_record_lines_tester.html',1,'']]],
  ['reinstalled_22',['ReInstalled',['../dc/d2a/struct_a_d_d_o_n_1_1_addon_events_1_1_re_installed.html',1,'ADDON::AddonEvents']]],
  ['remotetest_23',['RemoteTest',['../db/de6/class_remote_test.html',1,'']]],
  ['render_5fdetails_24',['render_details',['../d7/d1d/structrender__details.html',1,'']]],
  ['renderbufferpools_25',['RenderBufferPools',['../d5/d2a/struct_k_o_d_i_1_1_r_e_t_r_o_1_1_c_render_buffer_manager_1_1_render_buffer_pools.html',1,'KODI::RETRO::CRenderBufferManager']]],
  ['renderbuffertextures_26',['RenderBufferTextures',['../dc/d6f/struct_k_o_d_i_1_1_r_e_t_r_o_1_1_c_r_p_renderer_open_g_l_1_1_render_buffer_textures.html',1,'KODI::RETRO::CRPRendererOpenGL::RenderBufferTextures'],['../df/d17/struct_k_o_d_i_1_1_r_e_t_r_o_1_1_c_r_p_renderer_open_g_l_e_s_1_1_render_buffer_textures.html',1,'KODI::RETRO::CRPRendererOpenGLES::RenderBufferTextures'],['../df/d99/struct_k_o_d_i_1_1_r_e_t_r_o_1_1_c_r_p_win_renderer_1_1_render_buffer_textures.html',1,'KODI::RETRO::CRPWinRenderer::RenderBufferTextures']]],
  ['rendercapture_27',['RenderCapture',['../d0/dab/class_x_b_m_c_addon_1_1xbmc_1_1_render_capture.html',1,'XBMCAddon::xbmc']]],
  ['rendererdetail_28',['RendererDetail',['../d6/db1/struct_renderer_detail.html',1,'']]],
  ['renderitem_29',['RENDERITEM',['../d5/d28/struct_c_g_u_i_base_container_1_1_r_e_n_d_e_r_i_t_e_m.html',1,'CGUIBaseContainer']]],
  ['renderopts_30',['renderOpts',['../d0/d3f/struct_k_o_d_i_1_1_s_u_b_t_i_t_l_e_s_1_1_s_t_y_l_e_1_1render_opts.html',1,'KODI::SUBTITLES::STYLE']]],
  ['replaygain_31',['ReplayGain',['../d7/d7e/class_replay_gain.html',1,'']]],
  ['replaygainsettings_32',['ReplayGainSettings',['../db/dac/struct_c_application_volume_handling_1_1_replay_gain_settings.html',1,'CApplicationVolumeHandling']]],
  ['repoinfo_33',['RepoInfo',['../d7/ddd/struct_a_d_d_o_n_1_1_repo_info.html',1,'ADDON']]],
  ['repositorydirinfo_34',['RepositoryDirInfo',['../d1/d04/struct_a_d_d_o_n_1_1_repository_dir_info.html',1,'ADDON']]],
  ['repositoryupdated_35',['RepositoryUpdated',['../d2/db1/struct_a_d_d_o_n_1_1_c_repository_updater_1_1_repository_updated.html',1,'ADDON::CRepositoryUpdater']]],
  ['repoupdatedata_36',['RepoUpdateData',['../db/d85/struct_a_d_d_o_n_1_1_c_addon_database_1_1_repo_update_data.html',1,'ADDON::CAddonDatabase']]],
  ['resolution_37',['Resolution',['../d5/da3/struct_c_stream_details_1_1_resolution.html',1,'CStreamDetails']]],
  ['resolution_5finfo_38',['RESOLUTION_INFO',['../db/d94/struct_r_e_s_o_l_u_t_i_o_n___i_n_f_o.html',1,'']]],
  ['resolution_5fwhr_39',['RESOLUTION_WHR',['../d9/d18/struct_r_e_s_o_l_u_t_i_o_n___w_h_r.html',1,'']]],
  ['resolveresult_40',['ResolveResult',['../d2/da7/struct_a_d_d_o_n_1_1_c_repository_1_1_resolve_result.html',1,'ADDON::CRepository']]],
  ['resourceprioritysort_41',['ResourcePrioritySort',['../d2/dda/struct_u_p_n_p_1_1_resource_priority_sort.html',1,'UPNP']]],
  ['result_42',['Result',['../de/d04/classhelper___log_1_1_result.html',1,'helper_Log']]],
  ['result_5fset_43',['result_set',['../dc/d6e/classdbiplus_1_1result__set.html',1,'dbiplus']]],
  ['resumeinformation_44',['ResumeInformation',['../dd/dab/struct_k_o_d_i_1_1_v_i_d_e_o_1_1_u_t_i_l_s_1_1_resume_information.html',1,'KODI::VIDEO::UTILS']]],
  ['retardedasynccallbackhandler_45',['RetardedAsyncCallbackHandler',['../d8/d43/class_x_b_m_c_addon_1_1_retarded_async_callback_handler.html',1,'XBMCAddon']]],
  ['rssset_46',['RssSet',['../d2/db3/struct_rss_set.html',1,'']]],
  ['rt_5faddrinfo_47',['rt_addrinfo',['../df/dda/structrt__addrinfo.html',1,'']]],
  ['rt_5fmetrics_48',['rt_metrics',['../df/db3/structrt__metrics.html',1,'']]],
  ['rt_5fmsghdr_49',['rt_msghdr',['../d1/df2/structrt__msghdr.html',1,'']]],
  ['rt_5fmsghdr2_50',['rt_msghdr2',['../dc/de5/structrt__msghdr2.html',1,'']]],
  ['rtstat_51',['rtstat',['../de/d53/structrtstat.html',1,'']]],
  ['runinfo_52',['RunInfo',['../d4/df0/struct_c_g_u_i_font_t_t_f_1_1_run_info.html',1,'CGUIFontTTF']]]
];
