var searchData=
[
  ['c_0',['C++',['../d1/ddf/group__cpp.html',1,'']]],
  ['cachestatus_1',['class CacheStatus',['../d6/d53/group__cpp__kodi__vfs___defs___cache_status.html',1,'']]],
  ['caddonbase_2',['class CAddonBase',['../dc/d7b/group__cpp__kodi__addon__addonbase.html',1,'']]],
  ['caestream_3',['class CAEStream',['../d0/db0/group__cpp__kodi__audioengine___c_a_e_stream.html',1,'']]],
  ['callback_20functions_4',['3. Callback functions',['../db/d3b/group__cpp__kodi__addon__peripheral__callbacks.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_20on_5',['Callback functions from Kodi to Add-On',['../dd/d41/group__python___player_c_b.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_20on_6',['Callback functions from Kodi to add on',['../dd/d1b/group__cpp__kodi__gui__windows__window__callbacks.html',1,'Callback functions from Kodi to add-on'],['../d4/df8/group__python__xbmcgui__window__cb.html',1,'Callback functions from Kodi to add-on']]],
  ['callbacks_7',['Window Manager and Callbacks',['../d6/df1/group__winman.html',1,'']]],
  ['callbacks_20getdirectory_8',['Callbacks GetDirectory()',['../d8/dfe/group__cpp__kodi__addon__vfs__general__cb___get_directory.html',1,'']]],
  ['cdirentry_9',['class CDirEntry',['../d7/ded/group__cpp__kodi__vfs___c_dir_entry.html',1,'']]],
  ['cdllhelper_10',['class CDllHelper',['../dd/dea/group__cpp__kodi__tools___c_dll_helper.html',1,'']]],
  ['cendtime_11',['class CEndTime',['../d5/dd9/group__cpp__kodi__tools___c_end_time.html',1,'']]],
  ['cfile_12',['4. class CFile',['../d1/d6e/group__cpp__kodi__vfs___c_file.html',1,'']]],
  ['channel_13',['2. Channel',['../dd/dd7/group__cpp__kodi__addon__pvr___defs___channel.html',1,'']]],
  ['channel_20edit_20optional_14',['4. Channel edit (optional)',['../dd/dc5/group__cpp__kodi__addon__pvr__supports_channel_edit.html',1,'']]],
  ['channel_20group_15',['3. Channel Group',['../de/dfd/group__cpp__kodi__addon__pvr___defs___channel_group.html',1,'']]],
  ['channel_20groups_20optional_16',['3. Channel Groups (optional)',['../da/db1/group__cpp__kodi__addon__pvr__supports_channel_groups.html',1,'']]],
  ['channels_20required_17',['2. Channels (required)',['../df/d40/group__cpp__kodi__addon__pvr___channels.html',1,'']]],
  ['chapter_20optional_18',['6. Chapter (optional)',['../d6/d44/group__cpp__kodi__addon__inputstream___chapter.html',1,'']]],
  ['cheat_20operations_19',['6. Cheat operations',['../d3/d05/group__cpp__kodi__addon__game___cheat_operations.html',1,'']]],
  ['child_20functions_20',['Child Functions',['../dc/d01/group__cpp__kodi__gui__helpers__gl___c_shader_program__child.html',1,'']]],
  ['cinterfaceandroidsystem_21',['class CInterfaceAndroidSystem',['../da/d34/group__cpp__kodi__platform___c_interface_android_system.html',1,'']]],
  ['class_20audiodecoderinfotag_22',['class AudioDecoderInfoTag',['../d2/d69/group__cpp__kodi__addon__audiodecoder___defs___audio_decoder_info_tag.html',1,'']]],
  ['class_20audioencoderinfotag_23',['class AudioEncoderInfoTag',['../de/dfd/group__cpp__kodi__addon__audioencoder___defs___audio_encoder_info_tag.html',1,'']]],
  ['class_20audioengineformat_24',['class AudioEngineFormat',['../d2/de7/group__cpp__kodi__audioengine___defs___audio_engine_format.html',1,'']]],
  ['class_20cachestatus_25',['class CacheStatus',['../d6/d53/group__cpp__kodi__vfs___defs___cache_status.html',1,'']]],
  ['class_20caddonbase_26',['class CAddonBase',['../dc/d7b/group__cpp__kodi__addon__addonbase.html',1,'']]],
  ['class_20caestream_27',['class CAEStream',['../d0/db0/group__cpp__kodi__audioengine___c_a_e_stream.html',1,'']]],
  ['class_20cdirentry_28',['class CDirEntry',['../d7/ded/group__cpp__kodi__vfs___c_dir_entry.html',1,'']]],
  ['class_20cdllhelper_29',['class CDllHelper',['../dd/dea/group__cpp__kodi__tools___c_dll_helper.html',1,'']]],
  ['class_20cendtime_30',['class CEndTime',['../d5/dd9/group__cpp__kodi__tools___c_end_time.html',1,'']]],
  ['class_20cfile_31',['4. class CFile',['../d1/d6e/group__cpp__kodi__vfs___c_file.html',1,'']]],
  ['class_20cinterfaceandroidsystem_32',['class CInterfaceAndroidSystem',['../da/d34/group__cpp__kodi__platform___c_interface_android_system.html',1,'']]],
  ['class_20csettingvalue_33',['class CSettingValue',['../df/d58/group__cpp__kodi__addon__addonbase___defs___c_setting_value.html',1,'']]],
  ['class_20cthread_34',['class CThread',['../d4/dfd/group__cpp__kodi__tools___c_thread.html',1,'']]],
  ['class_20ctimer_35',['class CTimer',['../d2/d33/group__cpp__kodi__tools___c_timer.html',1,'']]],
  ['class_20driverprimitive_36',['class DriverPrimitive',['../d5/d57/group__cpp__kodi__addon__peripheral___defs___joystick___driver_primitive.html',1,'']]],
  ['class_20filestatus_37',['class FileStatus',['../df/d08/group__cpp__kodi__vfs___defs___file_status.html',1,'']]],
  ['class_20gamecontrollerlayout_38',['class GameControllerLayout',['../dd/d1e/group__cpp__kodi__addon__game___defs___input_types___game_controller_layout.html',1,'']]],
  ['class_20httpheader_39',['class HttpHeader',['../d9/d25/group__cpp__kodi__vfs___defs___http_header.html',1,'']]],
  ['class_20iinstanceinfo_40',['class IInstanceInfo',['../d2/dad/group__cpp__kodi__addon__addonbase___defs___i_instance_info.html',1,'']]],
  ['class_20imagedecoderinfotag_41',['class ImageDecoderInfoTag',['../d5/dff/group__cpp__kodi__addon__imagedecoder___defs___image_decoder_info_tag.html',1,'']]],
  ['class_20inputstreamcapabilities_42',['class InputstreamCapabilities',['../dc/d43/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_capabilities.html',1,'']]],
  ['class_20inputstreamcontentlightmetadata_43',['class InputstreamContentlightMetadata',['../d9/d31/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_contentlight_metadata.html',1,'']]],
  ['class_20inputstreamdvccmetadata_44',['class InputstreamDvccMetadata',['../d0/dd5/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_dvcc_metadata.html',1,'']]],
  ['class_20inputstreaminfo_45',['class InputstreamInfo',['../db/d82/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_info.html',1,'']]],
  ['class_20inputstreammasteringmetadata_46',['class InputstreamMasteringMetadata',['../da/d1e/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_mastering_metadata.html',1,'']]],
  ['class_20inputstreamproperty_47',['class InputstreamProperty',['../d6/df1/group__cpp__kodi__addon__inputstream___defs___inputstream_property.html',1,'']]],
  ['class_20inputstreamtimes_48',['class InputstreamTimes',['../dc/d8d/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_times.html',1,'']]],
  ['class_20itimercallback_49',['class ITimerCallback',['../df/de6/group__cpp__kodi__tools___c_timer___c_b.html',1,'']]],
  ['class_20joystick_50',['class Joystick',['../d0/da1/group__cpp__kodi__addon__peripheral___defs___joystick___joystick.html',1,'']]],
  ['class_20joystickfeature_51',['class JoystickFeature',['../db/d89/group__cpp__kodi__addon__peripheral___defs___joystick___joystick_feature.html',1,'']]],
  ['class_20peripheral_52',['class Peripheral',['../d3/da4/group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral.html',1,'']]],
  ['class_20peripheralcapabilities_53',['class PeripheralCapabilities',['../d6/dbe/group__cpp__kodi__addon__peripheral___defs___peripheral_capabilities.html',1,'']]],
  ['class_20peripheralevent_54',['class PeripheralEvent',['../d7/d89/group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral_event.html',1,'']]],
  ['class_20pvrcapabilities_55',['class PVRCapabilities',['../d3/df7/group__cpp__kodi__addon__pvr___defs___p_v_r_capabilities.html',1,'']]],
  ['class_20pvrchannel_56',['class PVRChannel',['../df/d03/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_channel.html',1,'']]],
  ['class_20pvrchannelgroup_57',['class PVRChannelGroup',['../d3/dec/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group.html',1,'']]],
  ['class_20pvrchannelgroupmember_58',['class PVRChannelGroupMember',['../de/da7/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group_member.html',1,'']]],
  ['class_20pvrchannelgroupmembersresultset_59',['class PVRChannelGroupMembersResultSet',['../d9/d7f/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group_members_result_set.html',1,'']]],
  ['class_20pvrchannelgroupsresultset_60',['class PVRChannelGroupsResultSet',['../d9/d68/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_groups_result_set.html',1,'']]],
  ['class_20pvrchannelsresultset_61',['class PVRChannelsResultSet',['../dc/d71/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_channels_result_set.html',1,'']]],
  ['class_20pvrcodec_62',['class PVRCodec',['../d1/d0c/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_codec.html',1,'']]],
  ['class_20pvrdescrambleinfo_63',['class PVRDescrambleInfo',['../df/d52/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_descramble_info.html',1,'']]],
  ['class_20pvredlentry_64',['class PVREDLEntry',['../d7/d48/group__cpp__kodi__addon__pvr___defs___e_d_l_entry___p_v_r_e_d_l_entry.html',1,'']]],
  ['class_20pvrepgtag_65',['class PVREPGTag',['../d1/dfb/group__cpp__kodi__addon__pvr___defs__epg___p_v_r_e_p_g_tag.html',1,'']]],
  ['class_20pvrepgtagsresultset_66',['class PVREPGTagsResultSet',['../da/d89/group__cpp__kodi__addon__pvr___defs__epg___p_v_r_e_p_g_tags_result_set.html',1,'']]],
  ['class_20pvrintsettingdefinition_67',['class PVRIntSettingDefinition',['../d7/d23/group__cpp__kodi__addon__pvr___defs___p_v_r_int_setting_definition.html',1,'']]],
  ['class_20pvrmenuhook_68',['class PVRMenuhook',['../d5/db8/group__cpp__kodi__addon__pvr___defs___menuhook___p_v_r_menuhook.html',1,'']]],
  ['class_20pvrprovider_69',['class PVRProvider',['../d2/dd9/group__cpp__kodi__addon__pvr___defs___p_v_r_provider.html',1,'']]],
  ['class_20pvrprovidersresultset_70',['class PVRProvidersResultSet',['../d5/d91/group__cpp__kodi__addon__pvr___defs___p_v_r_providers_result_set.html',1,'']]],
  ['class_20pvrrecording_71',['class PVRRecording',['../d5/d9e/group__cpp__kodi__addon__pvr___defs___recording___p_v_r_recording.html',1,'']]],
  ['class_20pvrrecordingsresultset_72',['class PVRRecordingsResultSet',['../d0/dac/group__cpp__kodi__addon__pvr___defs___recording___p_v_r_recordings_result_set.html',1,'']]],
  ['class_20pvrsettingdefinition_73',['class PVRSettingDefinition',['../dc/d36/group__cpp__kodi__addon__pvr___defs___p_v_r_setting_definition.html',1,'']]],
  ['class_20pvrsettingkeyvaluepair_74',['class PVRSettingKeyValuePair',['../d9/dcb/group__cpp__kodi__addon__pvr___defs___general___p_v_r_setting_key_value_pair.html',1,'']]],
  ['class_20pvrsignalstatus_75',['class PVRSignalStatus',['../d8/dd4/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_signal_status.html',1,'']]],
  ['class_20pvrstreamproperties_76',['class PVRStreamProperties',['../dc/d27/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_properties.html',1,'']]],
  ['class_20pvrstreamproperty_77',['class PVRStreamProperty',['../d8/d5c/group__cpp__kodi__addon__pvr___defs___general___inputstream___p_v_r_stream_property.html',1,'']]],
  ['class_20pvrstreamproperty_20definition_20pvr_5fstream_5fproperty_78',['class PVRStreamProperty &amp; definition PVR_STREAM_PROPERTY',['../db/de7/group__cpp__kodi__addon__pvr___defs___general___inputstream.html',1,'']]],
  ['class_20pvrstreamtimes_79',['class PVRStreamTimes',['../de/d74/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_times.html',1,'']]],
  ['class_20pvrstringsettingdefinition_80',['class PVRStringSettingDefinition',['../d0/d73/group__cpp__kodi__addon__pvr___defs___p_v_r_string_setting_definition.html',1,'']]],
  ['class_20pvrtimer_81',['class PVRTimer',['../dd/dd8/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer.html',1,'']]],
  ['class_20pvrtimersresultset_82',['class PVRTimersResultSet',['../d8/d1b/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timers_result_set.html',1,'']]],
  ['class_20pvrtimertype_83',['class PVRTimerType',['../d4/dd4/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer_type.html',1,'']]],
  ['class_20pvrtypeintvalue_84',['class PVRTypeIntValue',['../d8/d9f/group__cpp__kodi__addon__pvr___defs___p_v_r_type_int_value.html',1,'']]],
  ['class_20pvrtypestringvalue_85',['class PVRTypeStringValue',['../d4/dbe/group__cpp__kodi__addon__pvr___defs___p_v_r_type_string_value.html',1,'']]],
  ['class_20streamcryptosession_86',['class StreamCryptoSession',['../dd/dba/group__cpp__kodi__addon__inputstream___defs___stream_encryption___stream_crypto_session.html',1,'']]],
  ['class_20stringutils_87',['class StringUtils',['../df/d5a/group__cpp__kodi__tools___string_utils.html',1,'']]],
  ['class_20vfsurl_88',['class VFSUrl',['../dd/d23/group__cpp__kodi__addon__vfs___defs___v_f_s_url.html',1,'']]],
  ['class_20videocodecinitdata_89',['class VideoCodecInitdata',['../d2/dbb/group__cpp__kodi__addon__videocodec___defs___video_codec_initdata.html',1,'']]],
  ['class_20visualizationtrack_90',['class VisualizationTrack',['../d1/d1e/group__cpp__kodi__addon__visualization___defs___visualization_track.html',1,'']]],
  ['class_3a_20cstream_91',['Class: CStream',['../d2/d9b/group__cpp__kodi__addon__game___operation___c_stream.html',1,'']]],
  ['classes_92',['Guilib classes',['../d4/dee/group__guilib.html',1,'']]],
  ['cmake_20addon_20creation_20structure_93',['CMake addon creation structure',['../d0/dbc/group__cpp__cmake.html',1,'']]],
  ['codec_94',['Video Codec',['../db/ddf/group__cpp__kodi__addon__videocodec.html',1,'']]],
  ['codec_95',['4. Stream codec',['../d8/dbe/group__cpp__kodi__addon__inputstream___defs___stream_codec.html',1,'']]],
  ['compare_96',['String compare',['../d4/d27/group__cpp__kodi__tools___string_utils___compare_control.html',1,'']]],
  ['configuration_97',['8. Button mapping (controller configuration)',['../df/d8c/group__cpp__kodi__addon__peripheral___docs___lifetime___button_mapping.html',1,'']]],
  ['constants_98',['2. Stream constants',['../da/d7f/group__cpp__kodi__addon__inputstream___defs___stream_constants.html',1,'']]],
  ['context_20menu_99',['Dialog Context Menu',['../de/d4c/group__cpp__kodi__gui__dialogs___context_menu.html',1,'']]],
  ['control_100',['Control',['../d9/d2a/group__python__xbmcgui__control.html',1,'']]],
  ['control_101',['1. Setting control',['../de/dca/group__cpp__kodi__settings.html',1,'']]],
  ['control_20button_102',['Control Button',['../d9/d72/group__cpp__kodi__gui__windows__controls___c_button.html',1,'']]],
  ['control_20edit_103',['Control Edit',['../d9/d7c/group__cpp__kodi__gui__windows__controls___c_edit.html',1,'']]],
  ['control_20fade_20label_104',['Control Fade Label',['../d2/d86/group__cpp__kodi__gui__windows__controls___c_fade_label.html',1,'']]],
  ['control_20image_105',['Control Image',['../d8/dea/group__cpp__kodi__gui__windows__controls___c_image.html',1,'']]],
  ['control_20label_106',['Control Label',['../d5/d2b/group__cpp__kodi__gui__windows__controls___c_label.html',1,'']]],
  ['control_20progress_107',['Control Progress',['../d0/d04/group__cpp__kodi__gui__windows__controls___c_progress.html',1,'']]],
  ['control_20radio_20button_108',['Control Radio Button',['../d2/d21/group__cpp__kodi__gui__windows__controls___c_radio_button.html',1,'']]],
  ['control_20rendering_109',['Control Rendering',['../dd/df5/group__cpp__kodi__gui__windows__controls___c_rendering.html',1,'']]],
  ['control_20settings_20slider_110',['Control Settings Slider',['../d1/dd9/group__cpp__kodi__gui__windows__controls___c_settings_slider.html',1,'']]],
  ['control_20slider_111',['Control Slider',['../d9/d7f/group__cpp__kodi__gui__windows__controls___c_slider.html',1,'']]],
  ['control_20spin_112',['Control Spin',['../de/db4/group__cpp__kodi__gui__windows__controls___c_spin.html',1,'']]],
  ['control_20text_20box_113',['Control Text Box',['../df/d0b/group__cpp__kodi__gui__windows__controls___c_text_box.html',1,'']]],
  ['controlbutton_114',['Subclass - ControlButton',['../dc/d18/group__python__xbmcgui__control__button.html',1,'']]],
  ['controledit_115',['Subclass - ControlEdit',['../d4/d8b/group__python__xbmcgui__control__edit.html',1,'']]],
  ['controlfadelabel_116',['Subclass - ControlFadeLabel',['../dc/d41/group__python__xbmcgui__control__fadelabel.html',1,'']]],
  ['controlgroup_117',['Subclass - ControlGroup',['../da/d1f/group__python__xbmcgui__control__group.html',1,'']]],
  ['controlimage_118',['Subclass - ControlImage',['../d5/dec/group__python__xbmcgui__control__image.html',1,'']]],
  ['controllabel_119',['Subclass - ControlLabel',['../d4/dd9/group__python__xbmcgui__control__label.html',1,'']]],
  ['controller_120',['5. Mapping driver elements to the system&apos;s controller',['../da/da9/group__cpp__kodi__addon__peripheral___docs___lifetime___driver_elements.html',1,'']]],
  ['controller_20configuration_121',['8. Button mapping (controller configuration)',['../df/d8c/group__cpp__kodi__addon__peripheral___docs___lifetime___button_mapping.html',1,'']]],
  ['controller_20input_122',['Controller Input',['../df/db3/group__cpp__kodi__addon__peripheral___docs___controller_input.html',1,'']]],
  ['controller_20profiles_123',['1. Controller profiles',['../da/dc3/group__cpp__kodi__addon__peripheral___docs___controller_input___profiles.html',1,'']]],
  ['controller_20to_20libretro_20s_20retropad_124',['6. Translating Kodi controller to libretro&apos;s &quot;RetroPad&quot;',['../db/d99/group__cpp__kodi__addon__peripheral___docs___lifetime___translating.html',1,'']]],
  ['controllist_125',['Subclass - ControlList',['../da/d30/group__python__xbmcgui__control__list.html',1,'']]],
  ['controlprogress_126',['Subclass - ControlProgress',['../d4/d4a/group__python__xbmcgui__control__progress.html',1,'']]],
  ['controlradiobutton_127',['Subclass - ControlRadioButton',['../d7/d8e/group__python__xbmcgui__control__radiobutton.html',1,'']]],
  ['controls_128',['Controls',['../dd/d87/group__controls.html',1,'']]],
  ['controls_20kodi_3a_3agui_3a_3acontrols_3a_3ac_129',['3. GUI controls (kodi::gui::controls::C...)',['../d5/d39/group__cpp__kodi__gui__windows__controls.html',1,'']]],
  ['controlslider_130',['Subclass - ControlSlider',['../d0/d9c/group__python__xbmcgui__control__slider.html',1,'']]],
  ['controlspin_131',['Subclass - ControlSpin',['../dd/d02/group__python__xbmcgui__control__spin.html',1,'']]],
  ['controltextbox_132',['Subclass - ControlTextBox',['../da/df5/group__python__xbmcgui__control__textbox.html',1,'']]],
  ['controlvideowindow_133',['Subclass - ControlVideoWindow',['../d1/d42/group__python__xbmcgui__control__videowindow.html',1,'']]],
  ['cpp_5fkodi_5faddon_5fshader_5fpreset_134',['Cpp_kodi_addon_shader_preset',['../da/dee/group__cpp__kodi__addon__shader__preset.html',1,'']]],
  ['creation_20structure_135',['CMake addon creation structure',['../d0/dbc/group__cpp__cmake.html',1,'']]],
  ['csettingvalue_136',['class CSettingValue',['../df/d58/group__cpp__kodi__addon__addonbase___defs___c_setting_value.html',1,'']]],
  ['cstream_137',['Class: CStream',['../d2/d9b/group__cpp__kodi__addon__game___operation___c_stream.html',1,'']]],
  ['cthread_138',['class CThread',['../d4/dfd/group__cpp__kodi__tools___c_thread.html',1,'']]],
  ['ctimer_139',['class CTimer',['../d2/d33/group__cpp__kodi__tools___c_timer.html',1,'']]],
  ['curloptiontype_140',['enum CURLOptiontype',['../d2/dbb/group__cpp__kodi__vfs___defs___c_u_r_l_optiontype.html',1,'']]]
];
