var searchData=
[
  ['d3dpalette_0',['D3DPalette',['../d5/d94/struct_d3_d_palette.html',1,'']]],
  ['d3dtexture_1',['D3DTexture',['../d3/ddf/struct_d3_d_texture.html',1,'']]],
  ['darwinembednowplayinginfomanager_2',['DarwinEmbedNowPlayingInfoManager',['../dc/dc2/interface_darwin_embed_now_playing_info_manager.html',1,'']]],
  ['database_3',['Database',['../d3/d50/classdbiplus_1_1_database.html',1,'dbiplus']]],
  ['databasesettings_4',['DatabaseSettings',['../d2/d70/class_database_settings.html',1,'']]],
  ['databaseutils_5',['DatabaseUtils',['../d4/dc0/class_database_utils.html',1,'']]],
  ['dataholder_6',['DataHolder',['../d7/d25/struct_data_holder.html',1,'']]],
  ['dataset_7',['Dataset',['../da/df6/classdbiplus_1_1_dataset.html',1,'dbiplus']]],
  ['datasetfieldinfo_8',['DatasetFieldInfo',['../d7/dcf/struct_c_database_1_1_dataset_field_info.html',1,'CDatabase']]],
  ['datasetlayout_9',['DatasetLayout',['../d7/d77/class_c_database_1_1_dataset_layout.html',1,'CDatabase']]],
  ['dberrors_10',['DbErrors',['../dd/d9e/classdbiplus_1_1_db_errors.html',1,'dbiplus']]],
  ['dbusmessagedeleter_11',['DBusMessageDeleter',['../d2/d95/struct_d_bus_message_deleter.html',1,'']]],
  ['debug_5finfo_5fplayer_12',['DEBUG_INFO_PLAYER',['../dd/ddd/struct_d_e_b_u_g___i_n_f_o___p_l_a_y_e_r.html',1,'']]],
  ['debug_5finfo_5frender_13',['DEBUG_INFO_RENDER',['../df/d94/struct_d_e_b_u_g___i_n_f_o___r_e_n_d_e_r.html',1,'']]],
  ['debug_5finfo_5fvideo_14',['DEBUG_INFO_VIDEO',['../d8/db1/struct_d_e_b_u_g___i_n_f_o___v_i_d_e_o.html',1,'']]],
  ['debugformattester_15',['DebugFormatTester',['../dc/d82/class_debug_format_tester.html',1,'']]],
  ['debuglogsharingpresenter_16',['DebugLogSharingPresenter',['../d2/d66/class_debug_log_sharing_presenter.html',1,'']]],
  ['defaultfiltershader_17',['DefaultFilterShader',['../d5/dea/class_shaders_1_1_g_l_1_1_default_filter_shader.html',1,'Shaders::GL::DefaultFilterShader'],['../dd/d08/class_shaders_1_1_g_l_e_s_1_1_default_filter_shader.html',1,'Shaders::GLES::DefaultFilterShader']]],
  ['delayedcallguard_18',['DelayedCallGuard',['../d9/d64/class_x_b_m_c_addon_1_1_delayed_call_guard.html',1,'XBMCAddon']]],
  ['delete_5fclirccontainer_19',['delete_CLircContainer',['../d8/d5a/struct_o_p_t_i_o_n_a_l_s_1_1delete___c_lirc_container.html',1,'OPTIONALS']]],
  ['delete_5fcvaapiproxy_20',['delete_CVaapiProxy',['../d7/dcf/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_win_system_gbm_e_g_l_context_1_1delete___c_vaapi_proxy.html',1,'KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::delete_CVaapiProxy'],['../d9/d95/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_w_a_y_l_a_n_d_1_1_c_win_system_wayland_e_g_l_context_g_l_1_1delete___c_vaapi_proxy.html',1,'KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::delete_CVaapiProxy'],['../da/dac/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_w_a_y_l_a_n_d_1_1_c_win_system_wayland_e_g_l_context_g_l_e_s_1_1delete___c_vaapi_proxy.html',1,'KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::delete_CVaapiProxy'],['../d3/d32/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_x11_1_1_c_win_system_x11_g_l_context_1_1delete___c_vaapi_proxy.html',1,'KODI::WINDOWING::X11::CWinSystemX11GLContext::delete_CVaapiProxy']]],
  ['deletestream_21',['DeleteStream',['../d2/d1d/struct_k_o_d_i_1_1_r_e_t_r_o_1_1_delete_stream.html',1,'KODI::RETRO']]],
  ['deltapair_22',['DeltaPair',['../d9/d7d/struct_k_o_d_i_1_1_r_e_t_r_o_1_1_c_delta_pair_memory_stream_1_1_delta_pair.html',1,'KODI::RETRO::CDeltaPairMemoryStream']]],
  ['demux_5fcrypto_5finfo_23',['DEMUX_CRYPTO_INFO',['../d2/d5f/struct_d_e_m_u_x___c_r_y_p_t_o___i_n_f_o.html',1,'']]],
  ['demux_5fpacket_24',['DEMUX_PACKET',['../db/de6/struct_d_e_m_u_x___p_a_c_k_e_t.html',1,'']]],
  ['demuxcryptoinfo_25',['DemuxCryptoInfo',['../d3/dcd/struct_demux_crypto_info.html',1,'']]],
  ['demuxcryptosession_26',['DemuxCryptoSession',['../d8/d8a/struct_demux_crypto_session.html',1,'']]],
  ['demuxpacket_27',['DemuxPacket',['../d5/d74/struct_demux_packet.html',1,'']]],
  ['dependencyinfo_28',['DependencyInfo',['../db/d7c/struct_a_d_d_o_n_1_1_dependency_info.html',1,'ADDON']]],
  ['derivedtype1_29',['DerivedType1',['../d4/d21/struct_derived_type1.html',1,'']]],
  ['derivedtype2_30',['DerivedType2',['../df/d0f/struct_derived_type2.html',1,'']]],
  ['derivedtype3_31',['DerivedType3',['../de/dbc/struct_derived_type3.html',1,'']]],
  ['desc_32',['Desc',['../d0/d18/struct_v_d_p_a_u_1_1_c_decoder_1_1_desc.html',1,'VDPAU::CDecoder']]],
  ['descgrandfatheredtests_33',['DescGrandfatheredTests',['../dc/d4f/class_desc_grandfathered_tests.html',1,'']]],
  ['descnegativetests_34',['DescNegativeTests',['../dc/df7/class_desc_negative_tests.html',1,'']]],
  ['descriptionsplittest_35',['DescriptionSplitTest',['../db/d5e/struct_description_split_test.html',1,'']]],
  ['descriptor_36',['Descriptor',['../de/d36/struct_x_f_i_l_e_1_1_descriptor.html',1,'XFILE']]],
  ['devicechangedecision_37',['DeviceChangeDecision',['../d6/d39/struct_active_a_e_1_1_i_n_t_e_r_n_a_l_1_1_device_change_decision.html',1,'ActiveAE::INTERNAL']]],
  ['deviceresources_38',['DeviceResources',['../db/df3/class_d_x_1_1_device_resources.html',1,'DX']]],
  ['dialog_39',['Dialog',['../da/d2a/class_x_b_m_c_addon_1_1xbmcgui_1_1_dialog.html',1,'XBMCAddon::xbmcgui']]],
  ['dialogokmessage_40',['DialogOKMessage',['../da/d25/struct_k_o_d_i_1_1_m_e_s_s_a_g_i_n_g_1_1_h_e_l_p_e_r_s_1_1_dialog_o_k_message.html',1,'KODI::MESSAGING::HELPERS']]],
  ['dialogokmessage_41',['DialogOkMessage',['../db/d62/struct_dialog_ok_message.html',1,'']]],
  ['dialogprogress_42',['DialogProgress',['../db/d29/class_x_b_m_c_addon_1_1xbmcgui_1_1_dialog_progress.html',1,'XBMCAddon::xbmcgui']]],
  ['dialogprogressbg_43',['DialogProgressBG',['../df/d5a/class_x_b_m_c_addon_1_1xbmcgui_1_1_dialog_progress_b_g.html',1,'XBMCAddon::xbmcgui']]],
  ['dialogyesnomessage_44',['DialogYesNoMessage',['../da/d1e/struct_k_o_d_i_1_1_m_e_s_s_a_g_i_n_g_1_1_h_e_l_p_e_r_s_1_1_dialog_yes_no_message.html',1,'KODI::MESSAGING::HELPERS']]],
  ['dictionary_45',['Dictionary',['../d4/d80/class_x_b_m_c_addon_1_1_dictionary.html',1,'XBMCAddon']]],
  ['dir_46',['DIR',['../d9/d31/struct_d_i_r.html',1,'']]],
  ['director_47',['Director',['../de/db1/class_python_bindings_1_1_director.html',1,'PythonBindings']]],
  ['dirent_48',['dirent',['../d5/de2/structdirent.html',1,'']]],
  ['disabled_49',['Disabled',['../d3/d2b/struct_a_d_d_o_n_1_1_addon_events_1_1_disabled.html',1,'ADDON::AddonEvents']]],
  ['disc_50',['Disc',['../d4/d81/struct_disc.html',1,'']]],
  ['discinfo_51',['DiscInfo',['../d2/d98/struct_u_t_i_l_s_1_1_d_i_s_c_s_1_1_disc_info.html',1,'UTILS::DISCS']]],
  ['discstubtest_52',['DiscStubTest',['../d8/d64/class_disc_stub_test.html',1,'']]],
  ['displayconfigid_53',['DisplayConfigId',['../da/d11/struct_c_display_utils_win32_1_1_display_config_id.html',1,'CDisplayUtilsWin32']]],
  ['dist_5fsink_54',['dist_sink',['../d6/dc4/classspdlog_1_1sinks_1_1dist__sink.html',1,'spdlog::sinks']]],
  ['dlladdon_55',['DllAddon',['../d1/d51/class_dll_addon.html',1,'']]],
  ['dlladdoninterface_56',['DllAddonInterface',['../d8/d2a/class_dll_addon_interface.html',1,'']]],
  ['dlldvdnav_57',['DllDvdNav',['../d9/d93/class_dll_dvd_nav.html',1,'']]],
  ['dlldvdnavinterface_58',['DllDvdNavInterface',['../db/dbd/class_dll_dvd_nav_interface.html',1,'']]],
  ['dlldynamic_59',['DllDynamic',['../da/d5d/class_dll_dynamic.html',1,'']]],
  ['dlllibcurl_60',['DllLibCurl',['../d6/d0c/class_x_c_u_r_l_1_1_dll_lib_curl.html',1,'XCURL']]],
  ['dlllibcurlglobal_61',['DllLibCurlGlobal',['../d3/dd9/class_x_c_u_r_l_1_1_dll_lib_curl_global.html',1,'XCURL']]],
  ['dlllibsse4_62',['DllLibSSE4',['../dd/d4f/class_dll_lib_s_s_e4.html',1,'']]],
  ['dlllibsse4interface_63',['DllLibSSE4Interface',['../d6/dc8/class_dll_lib_s_s_e4_interface.html',1,'']]],
  ['dllloadercontainer_64',['DllLoaderContainer',['../da/d45/class_dll_loader_container.html',1,'']]],
  ['driverhandler_65',['DriverHandler',['../d3/dad/struct_p_e_r_i_p_h_e_r_a_l_s_1_1_c_peripheral_joystick_1_1_driver_handler.html',1,'PERIPHERALS::CPeripheralJoystick']]],
  ['driverprimitive_66',['DriverPrimitive',['../de/d51/structkodi_1_1addon_1_1_driver_primitive.html',1,'kodi::addon']]],
  ['drm_5ffb_67',['drm_fb',['../d0/da4/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1drm__fb.html',1,'KODI::WINDOWING::GBM']]],
  ['drmmodeobjectpropertiesdeleter_68',['DrmModeObjectPropertiesDeleter',['../de/d13/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_d_r_m_object_1_1_drm_mode_object_properties_deleter.html',1,'KODI::WINDOWING::GBM::CDRMObject']]],
  ['drmmodepropertyresdeleter_69',['DrmModePropertyResDeleter',['../d9/d4d/struct_k_o_d_i_1_1_w_i_n_d_o_w_i_n_g_1_1_g_b_m_1_1_c_d_r_m_object_1_1_drm_mode_property_res_deleter.html',1,'KODI::WINDOWING::GBM::CDRMObject']]],
  ['dummyjob_70',['DummyJob',['../d4/d86/class_dummy_job.html',1,'']]],
  ['dvdmessagelistitem_71',['DVDMessageListItem',['../dd/d72/struct_d_v_d_message_list_item.html',1,'']]],
  ['dvdstate_72',['DVDState',['../d6/d23/struct_d_v_d_state.html',1,'']]],
  ['dxgicolorspaceargs_73',['DXGIColorSpaceArgs',['../da/d91/struct_d_x_v_a_1_1_d_x_g_i_color_space_args.html',1,'DXVA']]],
  ['dxva2_5fmode_5ft_74',['dxva2_mode_t',['../d9/dc9/structdxva2__mode__t.html',1,'']]],
  ['dynamiccstructhdl_75',['DynamicCStructHdl',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrcapabilities_2c_20pvr_5faddon_5fcapabilities_20_3e_76',['DynamicCStructHdl&lt; PVRCapabilities, PVR_ADDON_CAPABILITIES &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrchannel_2c_20pvr_5fchannel_20_3e_77',['DynamicCStructHdl&lt; PVRChannel, PVR_CHANNEL &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrchannelgroup_2c_20pvr_5fchannel_5fgroup_20_3e_78',['DynamicCStructHdl&lt; PVRChannelGroup, PVR_CHANNEL_GROUP &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrchannelgroupmember_2c_20pvr_5fchannel_5fgroup_5fmember_20_3e_79',['DynamicCStructHdl&lt; PVRChannelGroupMember, PVR_CHANNEL_GROUP_MEMBER &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrdescrambleinfo_2c_20pvr_5fdescramble_5finfo_20_3e_80',['DynamicCStructHdl&lt; PVRDescrambleInfo, PVR_DESCRAMBLE_INFO &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrepgtag_2c_20epg_5ftag_20_3e_81',['DynamicCStructHdl&lt; PVREPGTag, EPG_TAG &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrintsettingdefinition_2c_20pvr_5fint_5fsetting_5fdefinition_20_3e_82',['DynamicCStructHdl&lt; PVRIntSettingDefinition, PVR_INT_SETTING_DEFINITION &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrprovider_2c_20pvr_5fprovider_20_3e_83',['DynamicCStructHdl&lt; PVRProvider, PVR_PROVIDER &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrrecording_2c_20pvr_5frecording_20_3e_84',['DynamicCStructHdl&lt; PVRRecording, PVR_RECORDING &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrsettingdefinition_2c_20pvr_5fsetting_5fdefinition_20_3e_85',['DynamicCStructHdl&lt; PVRSettingDefinition, PVR_SETTING_DEFINITION &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrsettingkeyvaluepair_2c_20pvr_5fsetting_5fkey_5fvalue_5fpair_20_3e_86',['DynamicCStructHdl&lt; PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrsignalstatus_2c_20pvr_5fsignal_5fstatus_20_3e_87',['DynamicCStructHdl&lt; PVRSignalStatus, PVR_SIGNAL_STATUS &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrstreamproperty_2c_20pvr_5fnamed_5fvalue_20_3e_88',['DynamicCStructHdl&lt; PVRStreamProperty, PVR_NAMED_VALUE &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrstringsettingdefinition_2c_20pvr_5fstring_5fsetting_5fdefinition_20_3e_89',['DynamicCStructHdl&lt; PVRStringSettingDefinition, PVR_STRING_SETTING_DEFINITION &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrtimer_2c_20pvr_5ftimer_20_3e_90',['DynamicCStructHdl&lt; PVRTimer, PVR_TIMER &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrtimertype_2c_20pvr_5ftimer_5ftype_20_3e_91',['DynamicCStructHdl&lt; PVRTimerType, PVR_TIMER_TYPE &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrtypeintvalue_2c_20pvr_5fattribute_5fint_5fvalue_20_3e_92',['DynamicCStructHdl&lt; PVRTypeIntValue, PVR_ATTRIBUTE_INT_VALUE &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]],
  ['dynamiccstructhdl_3c_20pvrtypestringvalue_2c_20pvr_5fattribute_5fstring_5fvalue_20_3e_93',['DynamicCStructHdl&lt; PVRTypeStringValue, PVR_ATTRIBUTE_STRING_VALUE &gt;',['../d7/d4f/classkodi_1_1addon_1_1_dynamic_c_struct_hdl.html',1,'kodi::addon']]]
];
